apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dockerfile-claim
  namespace: kaniko
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo
