apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: kaniko
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3ItYWRjLmludGVybmFsLm1lZGlhLm5ldCI6IHsKCQkJImF1dGgiOiAiY205aWIzUXJZMmt0WjJOd09tOUpVVGM1V1VoSGNIWnpWVVJRV1ZaMFduUlNUMXBxWXpWYU9XSmlRMnBTIgoJCX0sCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsKCQkJImF1dGgiOiAiYm1GbmNtazZSMnh2WW1Gc01USXpJVUFqIgoJCX0KCX0sCgkiY3JlZEhlbHBlcnMiOiB7CgkJInVzLWNlbnRyYWwxLWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIKCX0sCgkiZXhwZXJpbWVudGFsIjogImRpc2FibGVkIiwKCSJjdXJyZW50Q29udGV4dCI6ICJjb2xpbWEiCn0=
