apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      # args: [
      #     "--dockerfile=/workspace/dockerfile",
      #     "--context=dir://workspace",
      #     "--destination=nagri/dagri",
      #   ] # replace with your dockerhub account
      args: [ "--context=git@github.com:nagri/docker-images.git",
      "--context-sub-path=docker-images/docker-files/nginx/",
      "--dockerfile=/workspace/docker-images/docker-files/nginx/Dockerfile",
      "--destination=nagri/nginx:xyz" ]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: dockerfile-storage
          mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim
