apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: kaniko
spec:
  initContainers:
    - name: git-clone
      image: alpine
      command: ["sh", "-c"]
      args:
        - |
          apk add --no-cache git &&
          cd /workspace
          rm -rf *
          git clone https://github.com/nagri/docker-images.git
      volumeMounts:
        - name: dockerfile-storage
          mountPath: /workspace
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--context=/ocker-images/docker-files/nginx"
        - "--insecure"
        - "--destination=nagri/dagri"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
        - name: dockerfile-storage
          mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      persistentVolumeClaim:
        claimName: dockerfile-claim
