---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: stage
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
    spec:
      serviceAccount: service-gar
      containers:
        - name: nginx
          image: us-central1-docker.pkg.dev/nagri2909/nagri2909/container/nginx:1.23.3
          ports:
            - containerPort: 80
